### ISSUE TITLE
void clicks in carousel like slider

### ISSUE THREAD

**Issue by yesh** [metafizzy/flickity-docs#12]
hi,
is there a workaround to avoid the "no effects clicks" in this demo?
http://flickity.metafizzy.co/options.html#contain
this issue occours in the first and the last slides.

**Comment by desandro** [comment]
Thanks for your input. Could you explain what you mean by "no effects clicks"?

**Comment by yesh** [comment]
I'll try, I'm very unskilled at explaining things!
the following only applies on the "contain" demo.

if I am on the first slide and I click the next button there is a change only on the bullet nav, but there is no change/movement of the slides.
the same behaviour occours if i reach the fourth slide and I click the next button, there is no animation.

this is obviously because on the first and the fourth slides we already have the second and the fifth visible in the viewport and we are on the edges of the "contain mode".

it will be awesome if there is a workaround to remove the pagination points in wich we don't have an effective movement effect.

hope it helps. btw, great plugin! (:
