### ISSUE TITLE
Swipe distance

### ISSUE THREAD

**Issue by trinzia** [metafizzy/flickity-docs#13]
Hi desandro,
I am just testing flickity on Android and it seems the distance that I must swipe in order to move the slides is more than half of my screen width.  Is this so?  I would suggest that the swipe distance could be much smaller to make it work.
Thanks!

**Comment by desandro** [comment]
I believe this is a legitimate bug. I've moved the issue to the `flickity` repo. Thanks for reporting this  issue.
