### ISSUE TITLE
Image height missed in initial resize

### ISSUE THREAD

**Issue by JasonTheAdams** [metafizzy/flickity-docs#14]
First issue posted, so I have to say: flickity is awesome. Straight up. What a find. Bam. :)

I'm having one issue, however, that is pretty strange. The flickity slides consist of an image and some buttons underneath. When flickity first loads I get this chopped effect, wherein it's clearly only providing enough height for the buttons, but since they're beneath the image it just looks chopped.

If the browser is resized, or I wait a second and call the resize function, then it snaps to the perfect height. I'm also swapping out sets of slides in the same flickity, and when I do this the same issue happens.

It seems as though flickity calculates the height before the image has a chance to load and provide its height.

**Comment by JasonTheAdams** [comment]
Bah, I'm sorry, I just realized I put this in the docs instead of the flickity repo. I'll close and move this.

**Comment by Fabien3DArtist** [comment]
Hi Jason 
I got the same issue. 
Did you find why and how correct that problem ? 
Thanks

**Comment by JasonTheAdams** [comment]
H! @Fabien3DArtist I moved this here: https://github.com/metafizzy/flickity/issues/157
