### ISSUE TITLE
Multiple galleries, next triggers on all of them

### ISSUE THREAD

**Issue by sanschaise** [metafizzy/flickity-docs#15]
If you have multiple galleries 

var $gallery = $('.gallery').flickity({
  prevNextButtons: false,
  pageDots: true,
  contain:true,

});

$('.gallery-item').on( 'click', function() {
  $gallery.flickity( 'next', true );
});

will trigger on all the galleries on a page... 

Is there a way to trigger it on $(this).parent() ?

**Comment by desandro** [comment]
Yes, try:

``` js
$('.gallery-item').on( 'click', function() {
  $(this).parents('.gallery').flickity( 'next', true );
});
```

**Comment by sanschaise** [comment]
Perfect!! Thank you!
