### ISSUE TITLE
Newbie - Images not showing

### ISSUE THREAD

**Issue by abosarge** [metafizzy/flickity-docs#18]
Hi! I'm sure this is a user error, I'm pretty new to coding, but my images don't seem to be showing up. I'm not sure what I'm doing wrong, can you help? Thanks in advance. https://github.com/abosarge/Cookbook

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by abosarge** [comment]
Does this work? http://codepen.io/anon/pen/rOxVea 
I'm pretty new to this and want to make sure I'm giving you enough info. I have linkt to: 
flickity.pkgd.min.js
flickity.css
That seems to be creating the flickity structure, but the images are disappearing on the page.

**Comment by desandro** [comment]
Thanks for that! Looks like you need to use [`imagesLoaded` option](http://flickity.metafizzy.co/options.html#imagesloaded) or the [`lazyLoad` option](http://flickity.metafizzy.co/options.html#lazyload)

**Comment by abosarge** [comment]
Thanks! That solved it!
