### ISSUE TITLE
Multiple Gallery Cells Per Selected State

### ISSUE THREAD

**Issue by skyhartman** [metafizzy/flickity-docs#19]
Instead of only having one gallery cell as the selected cell, is there any way to have multiple gallery cells per the "selected cell" view at different breakpoints? Example of what I want:

Desktop
1. 4 gallery cells / 0 Dots showing

Tablet
1. 4 gallery cells / 2 gallery cells per selected state / 2 dots showing 

Mobile
1. 4 gallery cells / 1 gallery cell per selected state / 4 dots showing

**Comment by desandro** [comment]
You can use media queries to set different sizes for cells. See http://flickity.metafizzy.co/style.html#cell-style 

However, Flickity does not currently to align the cells differently. This request sounds similar to metafizzy/flickity#22  Closing this issue as a duplicate
