### ISSUE TITLE
'settle' example code listed incorrectly.

### ISSUE THREAD

**Issue by dom-turnbull** [metafizzy/flickity-docs#2]
Under http://flickity.metafizzy.co/api.html#events-demo, the following code is listed:

```
// jQuery
$gallery.on( 'select', function() {
  console.log( 'Flickity settled at ' + flkty.selectedIndex )
})
// vanilla JS
flkty.on( 'select', function() {...})
```

Which is actually the `'select'` event so when it is used, it fires too early and breaks code. 

**Resolved:** Sorted it by just changing `'select'` to `'settle'`.

**Comment by desandro** [comment]
Thanks for catching this! [If you like stickers](http://metafizzy.co/blog/flickity-beta-testing/), email me yo@metafizzy so I can send some your way.
