### ISSUE TITLE
Excess white space and draggable thumbnail row for synced carousel.

### ISSUE THREAD

**Issue by ghost** [metafizzy/flickity-docs#21]
Greetings, 

I've found your plugin recently and would like to thank for this very simple and cool tool. With it I've managed to create this kind of example: http://codepen.io/anon/pen/vNXrJL and my issue is:

How to make thumbnail block undraggable. I've tried to change draggable to false, but it kills the functionality and makes them unclickable.

**Comment by desandro** [comment]
If you'd prefer not to have a draggable thumbnail row, I recommend creating your own custom navigation with Flickity's API. See [Flickity - custom navigation UI](http://flickity.metafizzy.co/extras.html#custom-navigation-ui)
