### ISSUE TITLE
Center image vertically

### ISSUE THREAD

**Issue by marviobezerra** [metafizzy/flickity-docs#23]
How do the centralized image vertically?

**Comment by desandro** [comment]
With your own CSS. See https://css-tricks.com/centering-css-complete-guide/

**Comment by oksas** [comment]
Just wanted to drop a quick solution here for anyone else like myself that had this problem but struggled for a bit on a solution. I thought there would be more trouble doing this than there actually was, but it's as easy as David's comment makes it sound. I was thinking the absolute positioning that Flickity uses would cause some trouble, but it was seriously just as simple as adding this code:

``` css
.flickity-slider {
  display: flex;
  align-items: center;
}
```

`.flickity-slider` is one of the elements that is created by Flickity, and is the container of all the images (cells) themselves. Here's a quick screen snippet of the element as seen in Chrome's devtools:

![screen shot 2016-10-29 at 10 52 46 am](https://cloud.githubusercontent.com/assets/13337954/19831748/76547122-9dc6-11e6-8531-23b0761354dd.png)

Hope that helps someone!

**Comment by turnstylerj** [comment]
Just wanted to add to this thread if anyone else winds up here after Googling this - the above CSS works great, but was causing intermittent issues in my build with Flickity being unable to calculate positioning correctly with the flexbox wrapper. To solve it, I encapsulated it into a class I'm adding after the slider has initialized, in the `ready` event:
```
on: {
  ready: () => {
    carouselEl.classList.add('flexy-carousel');
  }
}
```
Then in the CSS, applying the styles above as `.flexy-carousel .flickity-slider {` instead. Hope this helps someone else!
