### ISSUE TITLE
How to handle FOUC ( Flash of Unstyled Content) with this Flikcity?

### ISSUE THREAD

**Issue by xcelpixel** [metafizzy/flickity-docs#25]
Hi,
I am facing FOUC with this slider. How to handle this? First on page loading all slides won't render properly( Stacked). I hope, you understand my issue.

Demo URL: http://33woodst.com/iac-beta/
Thanks

**Comment by xcelpixel** [comment]
buzzz?

**Comment by desandro** [comment]
Hide the gallery by default

``` css
.flick-gallery { opacity: 0; }
```

Then show it on doc ready

``` js
$(document).ready(function(){

  var $gallery = $('.flick-gallery').flickity({
     // options
    wrapAround: true,
    percentPosition: false,
    pageDots: false
  })

  // show gallery after Flickity enabled
  $gallery.css({ opacity: 1 });

});
```

I'm not sure what's taking so long for Flickity to load. It's running on document ready. I would look into why that takes long on your page.

**Comment by xcelpixel** [comment]
@desandro  Thank you so much!

**Comment by xcelpixel** [comment]
@desandro Sorry there's an issue! Whenever user comes on this website. It shows only arrow or you can say 40px height of the gallery.By clicking refresh again or windows resize, it starts working properly. 

Please have a look. 
Thanks

**Comment by desandro** [comment]
Sorry, but I am not available for personal support.
