### ISSUE TITLE
images not drawing in second tab of bootstrap framework.

### ISSUE THREAD

**Issue by MyAalteredRiots** [metafizzy/flickity-docs#27]
So I tried to get multiple sliders running in some bootstrap tabs. The first slider draws and works fine in the first tab. The second one doesn't display in the second tab until I resize the window or inspect an element. Is there a function I can call to redraw after I have a user click any subsequent tabs?

**Comment by desandro** [comment]
Yes, [call `resize`](http://flickity.metafizzy.co/api.html#resize). Thanks for reporting this issue

**Comment by warrebuysse** [comment]
@MyAalteredRiots: not sure "resize" is what you need. I'm pretty sure the carousel-cells don't have a dedicated width. Try to add width:100% to the cell and see what happens.
