### ISSUE TITLE
Lazyload affecting cell position after resize

### ISSUE THREAD

**Issue by ac70** [metafizzy/flickity-docs#29]
I still need to set up a simple example of this in Codepen, but thought I'd check to see if anyone knew about this off the toppa.
With lazyloading on (value: 2), when the screen is resized the gallery cells that have not yet been lazyloaded are positioned incorrectly in the main-gallery frame.

Lazyloading: false >> problem goes away.

suggestions?   has anyone else noticed this?

thanks much!  and LOVE FLICKITY!
-erc

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).
