### ISSUE TITLE
options.html need to flip between pageDots and prevNextButtons

### ISSUE THREAD

**Issue by boynet** [metafizzy/flickity-docs#30]
the prevNextButtons demo show the pageDots
and pageDots demo show the prevNextButtons

http://flickity.metafizzy.co/options.html#prevnextbuttons
http://flickity.metafizzy.co/options.html#pagedots

**Comment by desandro** [comment]
Thanks for taking a look. I realize it's a bit confusing. Because both options are enabled by default, the demos show those options disabled.
