### ISSUE TITLE
Wraparound & Cellalign with less than 3 cells that are < 100% width causes display glitch

### ISSUE THREAD

**Issue by thinkflo** [metafizzy/flickity-docs#31]
When using wraparound and cellalign left with 2 cells which are less than 100% width, there is a display bug when advancing next and then hitting the wraparound. Cell 1 ungracefully snaps off the viewport and disappears.  Appears ok when width is 100% but not when less.

http://codepen.io/anon/pen/zvXVBm

**Comment by desandro** [comment]
Thanks for reporting this issue. See https://github.com/metafizzy/flickity/issues/95#issuecomment-86124653
