### ISSUE TITLE
Initialize with HTML : slider needs reloead sometimes

### ISSUE THREAD

**Issue by alex4allofyou** [metafizzy/flickity-docs#32]
Otherwise it will be half its size. And when it is it needs a reload to show full height again, very annoying.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).
