### ISSUE TITLE
Autoscroll on left/right button hover

### ISSUE THREAD

**Issue by ghost** [metafizzy/flickity-docs#34]
Hi, I'd like to know if it's a built in feature that allows the left/right button functionality to work on hover, rather than click.
Thanks

**Comment by desandro** [comment]
No, there is not an option for next/previous on hover, but you could make it yourself with [Flickity's API](http://flickity.metafizzy.co/api.html). See [custom nav UI](http://flickity.metafizzy.co/extras.html#custom-navigation-ui) for a good demo to work with.
