### ISSUE TITLE
Disable horizontal scrolling on thumbnails

### ISSUE THREAD

**Issue by ghost** [metafizzy/flickity-docs#36]
Hey guys,

I'm looking for a way to disable the horizontal scrolling through the thumbnails as I will always be using 4 images in total on my site: vlieglesdeal.nl (for example go to: /rotterdam/ )

Thanks in advance!

**Comment by desandro** [comment]
Hello! Thanks for using Flickity :)

Unfortunately, Flickity does not have an option for this feature just yet. Subscribe to metafizzy/flickity#187 for any updates.
