### ISSUE TITLE
Unable to recognize the end of content

### ISSUE THREAD

**Issue by ottokovarik** [metafizzy/flickity-docs#37]
Hi, 
I have problem with this settings: http://flickity.metafizzy.co/options.html#contain
I don't want to move more then "the end" of content (to get the last slide into to the center of content).

But with actual working, next button is disabled after really last item is active. Even if transform is the same for last 4 items for example.

Is there any posibility how to recognize, that slider is on the end?

**Comment by desandro** [comment]
Thanks for reporting this issue. See https://github.com/metafizzy/flickity/issues/289#issuecomment-157488885 for discussion
