### ISSUE TITLE
White space gallery when scrolling down

### ISSUE THREAD

**Issue by ghost** [metafizzy/flickity-docs#38]
Hey guys,
Please check out this screencast I made of an issue I am having with my website vlieglesdeal.nl. I'm sorry it is in Dutch but I hope you guys understand it.
[https://youtu.be/PDh2Lux1DeE](https://youtu.be/PDh2Lux1DeE)
flatsome.uxthemes.com doesn't have the issue, so it is pretty weird I think.
I've also tried deleting my custom css, unfortunately that didn't resolve the issue.
Thanks a lot!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by ghost** [comment]
Hey David,

I'm unable to find a developer that can provide a reduced test case for me, unfortunately. I am though very willing to pay you(r team) to find and fix the bug. I hope to hear from you, thanks in advance!

**Comment by ghost** [comment]
![2](https://cloud.githubusercontent.com/assets/16964690/13120479/4a032ac2-d5ae-11e5-9795-2360140de162.jpg)
![1](https://cloud.githubusercontent.com/assets/16964690/13120481/4b871c3c-d5ae-11e5-8b79-e8f67f12171c.jpg)
Hey David, so we figured out it doesn't load in the auto height with the first image... Any ideas?

**Comment by ghost** [comment]
To cover it better: The auto height of the flickity-slider is not or incorrect loaded, as a result the white space appears. After the first image the flickity-slider gets the right value.

**Comment by desandro** [comment]
Sounds like a bug with imagesLoaded. Sorry, without a reduced test case I cannot debug this issue. Please open a new issue on the [main Flickity issue tracker](https://github.com/metafizzy/flickity/issues) if you would like me to take another look.
