### ISSUE TITLE
Adding js-flickity class hides the images

### ISSUE THREAD

**Issue by sushaantu** [metafizzy/flickity-docs#39]
I am trying to recreate UI of a different library with flickity which you you can see on: http://codepen.io/sushimashi/pen/mVgyve

However when I add the class "js-flickity" to the "gallery" class it hides the  images and renders the custom navigation useless.

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Flickity. Looks like this demo has two initializations: one in the HTML and one in the JavaScript. You only need one. If you remove the HTML init code, it works: See demo http://codepen.io/desandro/pen/2095ef67245daefc0715f2d932e3104f/
