### ISSUE TITLE
Pressing next / back buttons on iPad jumps 2 carousel-cells

### ISSUE THREAD

**Issue by PopcornDesign** [metafizzy/flickity-docs#42]
Hello, I am noticing a problem on iPad 3 Retina. When I click on next / back buttons it slides forward or backwards 2 carousel-cells. This is on Safari and Chrome on iPad only not iPhone.

Carousel looks and works great on all other devices.

**Comment by desandro** [comment]
Thanks for reporting this issue. See metafizzy/flickity#363
