### ISSUE TITLE
Change images for small viewports

### ISSUE THREAD

**Issue by FreddieT** [metafizzy/flickity-docs#44]
Is there a way to change images for small viewports? I'd like to swap images when the viewport gets below 500px.

**Comment by desandro** [comment]
There is no automatic way to do this with Flickity, but consider how you would achieve this just in plain HTML & CSS, without Flickity. You can use these techniques inside the Flickity cell.

**Comment by FreddieT** [comment]
Hi Desandro,
Thanks for your response and your advice about solving this problem. And thank you for your very clever and very neat Flickity carousel!
FreddieT
