### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by alxmau** [metafizzy/flickity-docs#45]
Hi guys, I have a form I use where customers order things, I would like to use your carousel with it. Here is a mockup of what I would like to achieve. Any ideas how I could do that? 

![carousel](https://cloud.githubusercontent.com/assets/557139/15573094/ec0cd422-2387-11e6-91a2-66f7f61d2205.jpg)

**Comment by desandro** [comment]
Flickity allows you to use your own HTML and CSS within its cells. See this basic example: http://codepen.io/desandro/pen/b567f31dadb6e938e575720595665b9f
