### ISSUE TITLE
translateX start with 7,77%

### ISSUE THREAD

**Issue by hb-dp303** [metafizzy/flickity-docs#46]
Hello, 
i have an issue with the Flickity PACKAGED v1.2.1

sorry for my english and my text. i am not a developer and english native speaker.

The yellow gap shouldn't be there
![flickity_screen_1](https://cloud.githubusercontent.com/assets/19652158/15653216/d8f88bae-268b-11e6-99c7-b696c93cfee6.jpg)

here you see the code.
![flickity_screen_2](https://cloud.githubusercontent.com/assets/19652158/15653218/d8facd4c-268b-11e6-941b-7a70abfb1768.jpg)

![flickity_screen_3](https://cloud.githubusercontent.com/assets/19652158/15653217/d8f976fe-268b-11e6-9c39-45911ed842d3.jpg)

The transformX/7,77%) shouldn't be there.
if i switch to an other display resolution for mobile the transform: translateX is only (0.5%); 
and everything is fine.

if i switch back to Flickity PACKAGED v1.0.2 everything is fine with any diplay resolution -> transform: translateX(0.5%);

what can i do?
can you help me?

thank you

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
