### ISSUE TITLE
Hi.. Problem with width images in mobile device

### ISSUE THREAD

**Issue by KEz1988** [metafizzy/flickity-docs#47]
Hi.. I have a problem with the code. when I see the page on a mobile device that looks like this. Could you tell me how I can do to change the image size and fit in the width. 

![flick](https://cloud.githubusercontent.com/assets/19657075/15659751/804dae2a-26c8-11e6-9c17-d9d9c1882b4c.jpg)

I thought the code would work is this . Sorry for the English to use. I almost do not speak the language.

@media screen and ( max-width: 768px ) {
  /\* disable Flickity for large devices */
  .gallery:after {
    content: '';
  }
  .gallery-cell{
  width: 100%;
  height: auto;
  background: #8C8;
  counter-increment: gallery-cell;
}

}

**Comment by KEz1988** [comment]
now I have modified the code and it works fine when I see it on a mobile device,  but looks bad on the actual size from my notebook

.gallery-cell {
  width: 100%;
  height: auto ;
  background: #8C8;
  counter-increment: gallery-cell;
}
![flick](https://cloud.githubusercontent.com/assets/19657075/15671025/73cba82a-2720-11e6-8ae5-fa7ba2630be5.png)

I have also used this code, but not resize the width of the images

@media screen and ( max-width: 768px ) {
  /\* disable Flickity for large devices */

```
.gallery-cell {
    width: 100%;
    heigh: auto;
}
```

}

but when I see the big picture looks bad haha I still do not solve it. Please help.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
