### ISSUE TITLE
nav/dots container

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [metafizzy/flickity-docs#48]
hi,
thanks again! for such a great plugin

how we can have a different nav/dots container? something like this option in owlCarousel http://www.owlcarousel.owlgraphic.com/docs/api-options.html#navcontainer

I know about apis http://flickity.metafizzy.co/extras.html.
but in my case it's a bit different and can't have predefined html markup. it will be good if we can pass a string for prevNextButtons option instead of just true/false. and this option will autoaticaly append navigation to that container
something like this http://codepen.io/Mohsen-Khakbiz/pen/jrMxEq

**Comment by desandro** [comment]
Thanks for this feature request. Sorry, but Flickity does not currently support this feature. But you can override Flickity default CSS for `.flickity-page-dots`. See http://flickity.metafizzy.co/style.html#page-dots

**Comment by Mohsen-Khakbiz** [comment]
thanks for suggestion.
can we also have arrowShape for arrows those aren't generated via Flickity?

**Comment by desandro** [comment]
You can set custom SVG in `arrowShape`. See the second example http://flickity.metafizzy.co/options.html#arrowshape
