### ISSUE TITLE
using isotope alongside flickity

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [metafizzy/flickity-docs#50]
hi,

how we can properly use isotope and flickity together?
here's a demo of what I'm going to make http://codepen.io/Mohsen-Khakbiz/pen/OXRopP

but as you can see there problem is (in my opinion) in .flickity-viewport width. or it maybe something else.
can you please help me to correct this. it's been days I'm struggling with it

thanks

**Comment by desandro** [comment]
Sorry, Flickity and Isotope will not work together. They both change how items are laid out and will therefore conflict with one another. I recommend you choose one or the other.
