### ISSUE TITLE
Features requests

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [metafizzy/flickity-docs#51]
hi,

first of all can we have onInitial event?
and the second, add a classname to visible items, like this demo http://flickity.metafizzy.co/options.html#contain
first, second and third **.carousel-cell** elements have a classname like **.in-view** or something like this

**Comment by desandro** [comment]
> first of all can we have onInitial event?

What's your use case? Can you provide a [**reduced test case**](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues)?

> and the second, add a classname to visible items, like this demo

This request may be resolved with `groupCell` option coming in Flickity v2. See metafizzy/flickity#22
