### ISSUE TITLE
Calculating Width as Height

### ISSUE THREAD

**Issue by tomlapage** [metafizzy/flickity-docs#53]
I'm having an issue with Flickity calculating my carousel width as the height. 

It seemed to be working in my staging environment but now in production it is miscalculating the height to be the width of the slider. I know it may be environmentally something on the site but I'm curious if anyone can help or if it may be due to a javascript conflict that I'm not seeing. 

**Broken Production**
http://www.americanhotel.com/content/slidetest.aspx

**Working on Staging environment**
https://staging.americanhotel.com/content/american_hotel_registry_products.aspx

Thanks

**Comment by desandro** [comment]
Looks like you may need [imagesLoaded](https://flickity.metafizzy.co/options.html#imagesloaded) enabled
