### ISSUE TITLE
specifying cellAlign for both sides of the same cell

### ISSUE THREAD

**Issue by ganar** [metafizzy/flickity-docs#54]
I have the following problem: 2 cells that have 200% of the width of the viewport on a phone. I need to be able to _cellAlign_ to the left of the first cell at first and to the right of the cell when swiping right, then again to the left of the following cell. I need to be able to chose the cells that have this behaviour.

Is this possible? how?

**Comment by desandro** [comment]
> Is this possible? how?

Sorry, Flickity does not support this kind of behavior. You'll have to use a separate solution. Or break up your cells so they fit within the viewport.
