### ISSUE TITLE
Flickity Slider works only after window resize

### ISSUE THREAD

**Issue by EmilienRamos** [metafizzy/flickity-docs#58]
I'm working with Flickity Slider, and I have an issue.

Only the last image is shown. But when I resize window (just 1px), it works and it display all images.

**This is how I display flickity slider**

`
jQuery('.plansItemImagesSlider').flickity({
    autoPlay: 3000,
    imagesLoaded: true,
    pauseAutoPlayOnHover: true
});`

**WHAT I'VE TRIED**

Trying to simule a window resize :

`if (jQuery('.plansItemImagesSlider').length > 0){
    jQuery(window).resize();
}`

Trying to use Flickity doc :

`if (jQuery('.plansItemImagesSlider').length > 0){
    jQuery(this).flickity('reloadCells');
}` AND 
`if (jQuery('.plansItemImagesSlider').length > 0){
    jQuery(this).flickity('resize');
}`

But I'm getting an error : `flickity not initialized. Cannot call methods, i.e. $().flickity("reloadCells")`

I also tried to put it together :
`
jQuery('.plansItemImagesSlider').flickity({
    autoPlay: 3000,
    imagesLoaded: true,
    pauseAutoPlayOnHover: true
}, 'reposition' /* OR 'resize' */);`

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by EmilienRamos** [comment]
Well, it's very weird.
I'm using Flickity several times on my website.

For example, on HomePage, it's ok.
But on others pages it doesn't work. It's like my configuration is not good but I don't know what is wrong ...

I notice that property "left" is never loaded on child elements. But when I resize the window, it appear in HTML DOM. I will search a solution before create a reduced test case.

**Comment by Vendio-Websolutions** [comment]
Did you solve this problem in the end? I've exactly the same problem in my website right now.

**Comment by EmilienRamos** [comment]
Hello !
Yeah, I solved it, but it’s very complicated ..
I worked with Wordpress - Divi theme - Tabs module. So the issue is very specific.

I solved it by using builder on the web page, and not with the back office.

**Comment by niklasp** [comment]
i have the same issue and do not know how to fix

**Comment by dreit-p** [comment]
The bug still exists. I didn't see any reasons for it... One page works properly, another one doesn't.

**Comment by rodrigues-tiago** [comment]
I have the same problem, have no idea how to fix it :/

**Comment by rodrigues-tiago** [comment]
```
window.onload = function () {
  flkty.reloadCells()
  flkty.resize()
}
```

this worked for me

**Comment by rodrigues-tiago** [comment]
```
window.onload = () => {
  flkty.reloadCells()
  flkty.resize()
}
```
this worked for me
