### ISSUE TITLE
webpack configuration and flickity is not defined

### ISSUE THREAD

**Issue by sably** [metafizzy/flickity-docs#59]
hi
my webpack.config is:
`    module: {
        rules: [
                {
                test: require.resolve('flickity'),
                use: 'imports-loader?define=>false&this=>window',
            },
        ],
    },`
and my html is:
`<!DOCTYPE html>
<html>
<head>
    <title>Flickity</title>
    <meta name=viewport content="width=device-width, initial-scale=1">
    <script src="dist/vendor.js"></script>
    <script src="dist/app.js"></script>
</head>
<body>

<div class="sss"></div>

<script>
    
    var elem = document.querySelector('.sss');
    var flkty = new Flickity( elem, {
        cellAlign: 'left',
        contain: true
    });
   
</script>`

and imports-loader and Flickity installed  with npm
but still say Flickity in not defined?!!why?

**Comment by desandro** [comment]
See [Flickity & Webpack documentation](https://flickity.metafizzy.co/extras.html#webpack). With Flickity v2, you no longer nead the imports-loader.
