### ISSUE TITLE
Dragging hides IE10 browser window due to body blur()

### ISSUE THREAD

**Issue by timswalling** [metafizzy/flickity-docs#8]
I really like Flickity, but I'm having some problems with it in IE10. This appears to be related to the body element being blurred, which causes Internet Explorer to move the browser window behind all other non-minimised windows. (You can test this behaviour by running <code>document.body.blur()</code> in Internet Explorer's developer console when you have multiple windows open.)

I've created a [reduced test case](http://codepen.io/timswalling/pen/RPwRMb). The status at the top of the page shows whether the body is currently focused.

Steps to reproduce:
- Open the [reduced test case](http://codepen.io/timswalling/pen/RPwRMb) in Internet Explorer 10.
- Ensure that other windows are open behind the test case.
- Check that the body is the currently focused element by referring to the status at the top of the test case page. If it is not focused, click on an unfocusable element in the body (such as the status text).
- Click and drag the gallery.

Expected result:
- The gallery will follow the mouse's horizontal movement until the mouse button is released.

Actual result:
- The browser window moves behind other windows.
- When returning to the browser window, the gallery continues to follow the mouse's horizontal movement even though the mouse button is not pressed. This is resolved by clicking the mouse again.

**Comment by desandro** [comment]
Thanks so much for reporting this bug. I'm closing this issue here (with the docs repo) and opening over in the Flickity repo for better visibility
